after_build:
  - 7z a Novel-Downloader.zip %APPVEYOR_BUILD_FOLDER%\Novel-Downloader\Novel-Downloader\bin\Release\Novel-Downloader.exe %APPVEYOR_BUILD_FOLDER%\Novel-Downloader\Novel-Downloader\bin\Release\VersOne.Epub.dll %APPVEYOR_BUILD_FOLDER%\Novel-Downloader\Novel-Downloader\bin\Release\System.IO.Compression.dll

artifacts:
  - path: %APPVEYOR_BUILD_FOLDER%\Novel-Downloader\Novel-Downloader\bin\Release\Novel-Downloader.zip
    name: NovelDownloader